### ISSUE TITLE
Add History Feature

### ISSUE THREAD

**Issue by shounak-dev** [Shounak2001/Calculator#2]

**Comment by Kardelio** [comment]
Hey @shounak-dev if no one else has done this yet could I maybe do this task?
Also if so could you give me a little bit more information about how you would like this history feature to work, maybe how it should look, how the user could access it and how much history is stored?

**Comment by shounak-dev** [comment]
Sure..I think that there should be a history button and when user click on it, a dialog box should be open and maximum 5 history will show to the user.

**Comment by Kardelio** [comment]
Awesome ok sounds good!
Can the user interact with any of these history items or just view them and then close the dialog again?

**Comment by shounak-dev** [comment]
No....just view the history and close the dialog.

**Comment by Kardelio** [comment]
@shounak-dev addressed in PR: #10 

Let me know what you think

**Comment by shounak-dev** [comment]
Awesome....Thank You...this is really great work

**Comment by Kardelio** [comment]
<3 my pleasure! thanks for this oppurtunity
